# https://www.redhat.com/en/blog/five-nines-dnsmasq
no-resolv
all-servers
no-negcache
listen-address=::1,127.0.0.1
cache-size=10000

server=/signal/10.0.0.2
server=10.0.0.2
server=8.8.8.8
server=2001:4860:4860::8888
server=1.1.1.1
server=2606:4700:4700::1111
