#!/usr/bin/env bash

if [[ "${IS_WSL}" -eq 1 ]]; then
    echo "Detected WSL, Installing linux packages"

    echo "Installing packages"
    sudo apt-get update
    sudo apt-get install -y apt-transport-https
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get dist-upgrade -y
    sudo apt-get install -y --no-install-recommends \
        keychain \
        libffi-dev \
        libtool \
        libsasl2-dev \
        build-essential \
        sqlite3 \
        libsqlite3-dev \
        libpcsclite-dev \
        make \
        build-essential \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        wget \
        curl \
        llvm \
        libncurses5-dev \
        xz-utils \
        tk-dev \
        libxml2-dev \
        libxmlsec1-dev \
        libffi-dev \
        liblzma-dev \
        zsh

    echo "Installing Rust"
    curl https://sh.rustup.rs -sSf | sh -s -- -y
fi

echo "Copying wsl config"
sudo cp $(dirname $0)/configs/wsl.conf /etc/wsl.conf
