#!/usr/bin/env zsh

if [[ "${IS_WSL}" -eq 1 ]]; then
    echo "Detected WSL, Installing linux packages"

    set -x

    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get dist-upgrade -y
    sudo apt-get install -y --no-install-recommends \
        keychain \
        libffi-dev \
        libtool \
        libsasl2-dev \
        build-essential \
        sqlite3 \
        libsqlite3-dev \
        make \
        build-essential \
        libssl-dev \
        zlib1g-dev \
        libbz2-dev \
        libreadline-dev \
        libsqlite3-dev \
        wget \
        curl \
        llvm \
        libncurses5-dev \
        xz-utils \
        tk-dev \
        libxml2-dev \
        libxmlsec1-dev \
        libffi-dev \
        liblzma-dev
fi
