#!/usr/bin/env zsh
set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

### Install sdkman (formally gvm) http://sdkman.io/
if [ ! -d ~/.sdkman/bin ]; then
    echo "Installing sdkman"
    curl -s http://get.sdkman.io | bash > /dev/null

    mkdir -p ~/.sdkman/etc
    touch: ~/.sdkman/etc/config
    # don't use normal symlink mechanism as sdkman install just checks for the presence of ~/.sdkman
    ln -f $SCRIPT_DIR/.sdkman/etc/config ~/.sdkman/etc/config
fi
