#!/usr/bin/env zsh

if [ ! -d ${ZDOTDIR:-~}/.antidote ]; then
    git clone --depth=1 https://github.com/mattmc3/antidote.git ${ZDOTDIR:-~}/.antidote
else
    git -C ${ZDOTDIR:-~}/.antidote pull --depth=1
fi

source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote bundle <"$DOTFILES/antidote/.zsh_plugins.txt.symlink" >~/.zsh_plugins.zsh
