#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

DOTFILES_ROOT=$(pwd -P)

# Check for Homebrew
if test ! $(which brew)
then
  echo "  Installing Homebrew for you."

  # Install the correct homebrew for each OS type
  if test "$(uname)" = "Darwin"
  then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  elif test "$(expr substr $(uname -s) 1 5)" = "Linux"
  then
    sudo apt-get install build-essential curl file git
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
  fi

fi

HOMEBREW_DIR=$(brew --repo homebrew/core)
mkdir -p $HOMEBREW_DIR/.git/hooks
cp $DOTFILES_ROOT/homebrew/terragrunt_workaround_post_merge.sh $HOMEBREW_DIR/.git/hooks/post-merge

exit 0
