#!/usr/bin/env bash
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

set -e

DOTFILES_HOMEBREW_SCRIPT_DIR="$(dirname "$(realpath "$0")")"

# ensure PATH is setup correctly as we need to call brew
source $DOTFILES_HOMEBREW_SCRIPT_DIR/env.zsh

# Check for Homebrew
if test ! $(which brew)
then
  echo "  Installing Homebrew..."

  if test "$(expr substr $(uname -s) 1 5)" = "Linux"
  then
    sudo apt-get install build-essential curl file git
  fi

  bash -c "$(curl -fsSL  https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# if we had to install brew, load the path again
source $DOTFILES_HOMEBREW_SCRIPT_DIR/env.zsh

HOMEBREW_DIR=$(brew --repo homebrew/core)

exit 0
