#!/bin/sh
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

DOTFILES_ROOT=$(pwd -P)

# Check for Homebrew
if test ! $(which brew)
then
  echo "  Installing Homebrew..."

  if test "$(expr substr $(uname -s) 1 5)" = "Linux"
  then
    sudo apt-get install build-essential curl file git
  fi

  bash -c "$(curl -fsSL  https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

HOMEBREW_DIR=$(brew --repo homebrew/core)
mkdir -p $HOMEBREW_DIR/.git/hooks
cp $DOTFILES_ROOT/homebrew/terragrunt_workaround_post_merge.sh $HOMEBREW_DIR/.git/hooks/post-merge

exit 0
