#!/usr/bin/env zsh

SCRIPT_DIR="$(dirname "$(realpath "$0")")"

export PIPX_HOME="~/.local/pipx"

if [[ $(uname -s) == "Linux" ]]; then
  if ! dpkg -s python-setuptools &> /dev/null; then
    sudo apt-get update && sudo apt-get install -y python-setuptools python3-pip
  fi
else
  sudo easy_install pip
fi

pipx_install_requirements() {
  printf "\n-> Installing user Python packages with pipx...\n\n"
  PY="$(python3 --version)"
  PIPX_LIST="$(pipx list)"
  while read -r P; do
    [[ $P =~ "httpie" ]] && CMD="http" || CMD="$P"
    if [[ $(echo "$PIPX_LIST" | grep -ce "package $P .*, $PY") -gt 0 ]]; then
      echo "$P already installed."
    elif [[ $(echo "$PIPX_LIST" | grep -ce "package $P") -gt 0 ]]; then
      echo "Reinstalling $P for $PY."
      pipx uninstall "$P" && pipx install --python "$(command -v python3)" "$P"
    elif command -v "$CMD" &>/dev/null; then
      echo "$P already on PATH at $(command -v "$CMD")."
    else
      pipx install "$P"
    fi
  done <"$SCRIPT_DIR/requirements.txt"
}

pipx_install_requirements
