#!/usr/bin/env zsh

# Add bash completions subdirectory
# See https://github.com/scop/bash-completion/blob/master/README.md#faq
export BASH_COMPLETIONS_DIR=~/.local/share/bash-completion/completions

mkdir -p $BASH_COMPLETIONS_DIR
